### ISSUE TITLE
[F32a] Can't read instruction from partial data

### ISSUE THREAD

**Issue by Ray-1024** [ryukzak/wrench#22]
Without alignment case: http://wrench.edu.swampbuds.me/result/19c22d7c-965c-4271-a63d-bc87e585f3ec
With alignment case: http://wrench.edu.swampbuds.me/result/01a84ddd-5cc6-482b-bce6-3ff8338e4840

code:
```
   .data

input_address:        .word 0x80
output_address:       .word 0x84
alligment:            .word '................................'

    .text

_start:
    @p input_address  a! @
    @p input_address  a! @

    _abs
    over
    _abs
    over

    gcd

    @p output_address a! !
    halt


_abs:
    dup
    -if _already_positive
    inv
    lit 1
    +
_already_positive:
    ;


gcd:
    dup
    if gcd_end
    over
    a!
    dup
    b!
    lit 0
    lit 0
    +/
    drop
    next gcd
gcd_end:
    ;
```

configuration:
```
---
name: "gcd (18,27) == 9"
limit: 1000
memory_size: 1000
input_streams:
    0x80: [18, 27]
    0x84: []
reports:
    - name: Step-by-step log
      slice: all
      filter:
          - instruction
          - state
      inspector:
          - - T A B S
            - [register_hex, T]
            - [register_hex, A]
            - [register_hex, B]
            - [register_hex, S]
            - R
            - [register, R]
    - name: Check results
      slice: last
      filter:
          - state
      inspector:
          - ["numio[0x80]:", [number_io_stream, 0x0080]]
          - ["numio[0x84]:", [number_io_stream, 0x0084]]
```
