### ISSUE TITLE
Branch if greater issue (RISCIV)

### ISSUE THREAD

**Issue by Shir5** [ryukzak/wrench#23]
Version 0.0.0.4 (https://github.com/ryukzak/wrench/commit/5491c255c0cf2ca16878c9388b3d76d7407bb000) Wed Dec 4 00:18:18 2024
RISCIV arc 
### **Assembler code**

```
  .data
input_addr:       .word 0x80          ; Адрес числа n
output_addr:      .word 0x84          ; Адрес для сохранения результата

  .text
  _start:
  ; Загрузка входного числа
lui     t0, 0x0               ; t0 <- input_addr (старшие биты)
addi    t0, t0, 0x80          ; t0 <- полный адрес input_addr
lw      t1, 0(t0)             ; t1 <- n (само число)

  ; Приведение к абсолютному значению (n = abs(n))
li      t2, 0                 ; t2 <- 0 (нуль)
bgt     t1, t2, skip_abs      ; Если n >= 0, пропустить abs
sub     t1, t2, t1            ; n = -n (если n < 0)
  skip_abs:

  ; Инициализация для суммы цифр
li      t2, 0                 ; t2 <- 0 (сумма цифр)
li      t3, 10                ; t3 <- 10 (делитель для остатка)

  sum_loop:
  ; Проверка условия цикла (n > 0)
beqz    t1, end_sum           ; Если n == 0, выйти из цикла

  ; total += n % 10
rem     t4, t1, t3            ; t4 <- n % 10 (остаток)
add     t2, t2, t4            ; t2 <- t2 + t4 (обновить сумму)

  ; n //= 10
div     t1, t1, t3            ; t1 <- n // 10 (целочисленное деление)
j       sum_loop              ; Повторить цикл

  end_sum:
  ; Сохранение результата
lui     t0, 0x0               ; t0 <- output_addr (старшие биты)
addi    t0, t0, 0x84          ; t0 <- полный адрес output_addr
sw      t2, 0(t0)             ; *t0 = t2 (записать результат)

halt                          ; Завершение программы
```

### **YAML Configuration**

```
limit: 40
memory_size: 0x90
input_streams:
  0x80: [-456]
  132: []
reports:
  - name: Step-by-step log
    slice: all
    filter:
      - instruction
      - state
    inspector:
      - - [label, T0]
        - [register, T0]
        - [label, T1]
        - [register, T1]
        - T2
        - [register, T2]
        - T3
        - [register, T3]
        - T4
        - [register, T4]
        - T5
        - [register, T5]
        - T6
        - [register, T6]
      - ["0x80", [number_io_stream, 0x0080]]
      - ["0x84", [number_io_stream, 0x0084]]
  - name: Check results
    slice: last
    filter:
      - state
    inspector:
      - [[label, "numio[0x80]:"], [number_io_stream, 0x0080]]
      - [[label, "numio[0x84]:"], [number_io_stream, 0x0084]]
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [15]

```

### **Logging**

```
# Step-by-step log
8:	Lui {rd = T0, k = 0}  	@_start ;;
T0 0 T1 0 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-456] >>> []
0x84 [] >>> [] ;;
12:	Addi {rd = T0, rs1 = T0, k = 128} ;;
T0 128 T1 0 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-456] >>> []
0x84 [] >>> [] ;;
16:	Lw {rd = T1, offsetRs1 = MemRef {mrOffset = 0, mrReg = T0}} ;;
T0 128 T1 -456 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
20:	Li {rd = T2, k = 0} ;;
T0 128 T1 -456 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
24:	Bgt {rs1 = T1, rs2 = T2, k = 8} ;;
T0 128 T1 -456 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
32:	Li {rd = T2, k = 0}  	@skip_abs ;;
T0 128 T1 -456 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
36:	Li {rd = T3, k = 10} ;;
T0 128 T1 -456 T2 0 T3 10 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -456 T2 0 T3 10 T4 0 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -456 T2 0 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -456 T2 -6 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -46 T2 -6 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -46 T2 -6 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -46 T2 -6 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -46 T2 -6 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -46 T2 -12 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -5 T2 -12 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -5 T2 -12 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -5 T2 -12 T3 10 T4 -6 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -5 T2 -12 T3 10 T4 -5 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -5 T2 -17 T3 10 T4 -5 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -17 T3 10 T4 -5 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -1 T2 -17 T3 10 T4 -5 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -1 T2 -17 T3 10 T4 -5 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -17 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -1 T2 -18 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -18 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -1 T2 -18 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -1 T2 -18 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -18 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -1 T2 -19 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -19 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -1 T2 -19 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -1 T2 -19 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -19 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -1 T2 -20 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
52:	Div {rd = T1, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -20 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
56:	J {k = -16} ;;
T0 128 T1 -1 T2 -20 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
40:	Beqz {rs1 = T1, k = 20}  	@sum_loop ;;
T0 128 T1 -1 T2 -20 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
44:	Rem {rd = T4, rs1 = T1, rs2 = T3} ;;
T0 128 T1 -1 T2 -20 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
48:	Add {rd = T2, rs1 = T2, rs2 = T4} ;;
T0 128 T1 -1 T2 -21 T3 10 T4 -1 T5 0 T6 0
0x80 [] >>> []
0x84 [] >>> [] ;;
Instruction limit reached
---
# Check results
Instruction limit reached

ASSERTION FAIL, expect:
numio[0x80]: [] >>> []
numio[0x84]: [] >>> [15]

Diff:
1c1,2
< Instruction limit reached
---
> numio[0x80]: [] >>> []
> numio[0x84]: [] >>> [15]
```

**Comment**
When the input to the program is a negative number, the command BGT (Branch if Greater Than) incorrectly processes it as a positive number. This happens because the instruction does not correctly handle signed integers, potentially interpreting a negative value (e.g., -456 in two's complement representation) as a large positive value.

As a result, the condition for stopping the program is never met. Specifically:

- BGT fails to recognize that the negative value is less than zero.
- This causes the program to incorrectly skip the logic for converting the number to its absolute value.
- Consequently, the program enters an infinite loop, repeatedly processing a negative or invalid state, and never reaches the termination condition.

### **Test**

```
.text
_start:
    li t1, -10        ; Загрузить отрицательное число в t1
    li t2, 0          ; Загрузить ноль в t2

    bgt t1, t2, fail  ; Проверить: t1 > t2? Если да, перейти на fail
    li t3, 1          ; Если условие ложно, установить t3 = 1 (успех)
    j end             ; Перейти в конец программы

fail:
    li t3, 0          ; Если t1 > t2 (ошибка), установить t3 = 0

end:
    halt              ; Завершение программы

```

### **Test Configuration YAML**
```
limit: 40
memory_size: 0x90
input_streams:
  0x80: [-10]  # Тестовое значение t1
  0x84: []     # Результат будет записан сюда
reports:
  - name: Step-by-step log
    slice: all
    filter:
      - instruction
      - state
    inspector:
      - - [label, T0]
        - [register, T0]
        - [label, T1]
        - [register, T1]
        - T2
        - [register, T2]
        - T3
        - [register, T3]
        - T4
        - [register, T4]
        - T5
        - [register, T5]
        - T6
        - [register, T6]
      - ["0x80", [number_io_stream, 0x0080]]
      - ["0x84", [number_io_stream, 0x0084]]
  - name: Check results
    slice: last
    filter:
      - state
    inspector:
      - [[label, "numio[0x80]:"], [number_io_stream, 0x0080]]
      - [[label, "numio[0x84]:"], [number_io_stream, 0x0084]]
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [1]  # Ожидаемый результат: t3 = 1 (тест пройден)

```

### **Test Log**
```

# Step-by-step log
0:	Li {rd = T1, k = -10}  	@_start ;;
T0 0 T1 -10 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-10] >>> []
0x84 [] >>> [] ;;
4:	Li {rd = T2, k = 0} ;;
T0 0 T1 -10 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-10] >>> []
0x84 [] >>> [] ;;
8:	Bgt {rs1 = T1, rs2 = T2, k = 12} ;;
T0 0 T1 -10 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-10] >>> []
0x84 [] >>> [] ;;
20:	Li {rd = T3, k = 0}  	@fail ;;
T0 0 T1 -10 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-10] >>> []
0x84 [] >>> [] ;;
24:	Halt  	@end ;;
T0 0 T1 -10 T2 0 T3 0 T4 0 T5 0 T6 0
0x80 [-10] >>> []
0x84 [] >>> []
---
# Check results
numio[0x80]: [-10] >>> []
numio[0x84]: [] >>> []

ASSERTION FAIL, expect:
numio[0x80]: [] >>> []
numio[0x84]: [] >>> [1]  # Ожидаемый результат: t3 = 1 (тест пройден)

Diff:
1,2c1,2
< numio[0x80]: [-10] >>> []
< numio[0x84]: [] >>> []
---
> numio[0x80]: [] >>> []
> numio[0x84]: [] >>> [1]  # Ожидаемый результат: t3 = 1 (тест пройден)

```

### **Link to lab**
[[http://wrench.edu.swampbuds.me/result/8fb9427c-2e41-4ffe-b6d4-ce9f6a3eb880]](url)
