### ISSUE TITLE
RISC-IV-32: `sb` directive stores word instead of byte

### ISSUE THREAD

**Issue by lavrentious** [ryukzak/wrench#59]
**Describe the bug**
According to [RISCIV doc](https://github.com/ryukzak/wrench/blob/master/docs/risc-iv.md), `sb` instruction shall store the lower byte of a register into memory address:

> **Store Byte**
    - **Syntax:** `sb <rs2>, <offset>(<rs1>)`
    - **Description:** Store the lower 8 bits of the value from the source register into memory at the address computed by adding the offset to the base register.
    - **Operation:** `M[offset + rs1] <- rs2 & 0xFF`

However, it appears to function exactly like Store Word (`sw`) directive (the only difference being applying 0xFF mask with AND) - it stores the byte followed by 3 zero bytes

**To Reproduce**
1. Minimized program:
```
    .data
buf:             .byte  '________'         ; 8-byte buffer at 0x00
test_char:       .byte  'Z'

    .text
    .org     0x88
_start:
    ; t0 -- buf pointer
    ; t1 -- test char
    lui      t0, %hi(buf)                    ; load buffer pointer
    addi     t0, t0, %lo(buf)

    lui      t1, %hi(test_char)              ; load test char
    addi     t1, t1, %lo(test_char)
    lw       t1, 0(t1)

    sb       t1, 0(t0)                       ; write test char to buffer

    halt
```
2. Minimized YAML configuration and simulation log.
```
name: "risciv sb bug"
limit: 2000
memory_size: 0x1000
input_streams:
  0x80: []
  0x84: []
reports:
  - name: Step-by-step
    slice: all
    view: |
      {pc}:	{instruction}	{pc:label} buf_ptr=t0={T0:hex} char=t1={T1:hex}
  - name: Check results
    slice: last
    filter:
      - state
    view: |
      {memory:0:7}
    assert: |
      mem[0..7]: 	5a 5f 5f 5f 5f 5f 5f 5f
```
Output:
```
---
# Step-by-step
136:	Lui {rd = T0, k = 0}	@_start buf_ptr=t0=0x00000000 char=t1=0x00000000
140:	Addi {rd = T0, rs1 = T0, k = 0}	 buf_ptr=t0=0x00000000 char=t1=0x00000000
144:	Lui {rd = T1, k = 0}	 buf_ptr=t0=0x00000000 char=t1=0x00000000
148:	Addi {rd = T1, rs1 = T1, k = 8}	 buf_ptr=t0=0x00000000 char=t1=0x00000000
152:	Lw {rd = T1, offsetRs1 = MemRef {mrOffset = 0, mrReg = T1}}	 buf_ptr=t0=0x00000000 char=t1=0x00000008
156:	Sb {rs2 = T1, offsetRs1 = MemRef {mrOffset = 0, mrReg = T0}}	 buf_ptr=t0=0x00000000 char=t1=0x0000005a
160:	Halt	 buf_ptr=t0=0x00000000 char=t1=0x0000005a
---
# Check results
mem[0..7]: 	5a 00 00 00 5f 5f 5f 5f
ASSERTION FAIL, expect:
mem[0..7]: 	5a 5f 5f 5f 5f 5f 5f 5f
```
4. Link to the wrench report.
    https://wrench.edu.swampbuds.me/result/e6040ee0-8a60-45a5-aa5e-b3aff9eca623

**Expected behavior**
`sb` is expected to store exactly 1 byte without overwriting the remaining 3

**Additional context**
\-
