### ISSUE TITLE
Non-ANSI (cyrillic) symbols in the service input raise 500

### ISSUE THREAD

**Issue by guganchik** [ryukzak/wrench#7]
Version: 0.0.0.1 (f0a992b) Mon Oct 7 21:59:51 2024 +0200

Possible problems:

- docker image requires correct local setting.
- problem can be related to Text encoding/decoding on the haskell side.

## Assembler Code:

```
	.data
input_addr:    .word 0x80
output_addr:   .word 0x84
    .text
_start:
    lui      t0, input_addr
    addi     t0, t0, input_addr
    lw       t0, 0(t0)
    lw       t1, 0(t0)	
    li       t2, 1               ; t2 = 1
    bgt      t1, t2, invalid_input
    li       t2, 2

check_prime_loop:
    mul      t3, t2, t2
    bgt      t3, t1, prime

    rem      t4, t1, t2 
    beqz     t4, composite

    addi     t2, t2, 1
    j        check_prime_loop

composite:
    li       t5, 0
    j        write_output

prime:
    li       t5, 1
    j        write_output 

invalid_input:
    li      t5, 0
    j        write_output 
write_output:
    lui      t0, output_addr
    addi     t0, t0, output_addr
    lw       t0, 0(t0)
    sw       t5, 0(t0)

    halt
```

## Config (YAML):

```
limit: 40
memory_size: 0x90
input_streams:
  0x80: [-1]  # Пример входных данных
  132: []
reports:
  - name: Step-by-step log
    slice: all
    filter:
      - instruction
      - state
    inspector:
      - - [label, T0]
        - [register, T0]
        - [label, T1]
        - [register, T1]
        - T2
        - [register, T2]
      - ["0x80", [number_io_stream, 0x0080]]
      - ["0x84", [number_io_stream, 0x0084]]
  - name: Check results
    slice: last
    filter:
      - state
    inspector:
      - [[label, "numio[0x80]:"], [number_io_stream, 0x0080]]
      - [[label, "numio[0x84]:"], [number_io_stream, 0x0084]]
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [0]
```
